language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-23.0.1
  - android-23
  - extra-android-support
  - extra
  - extra-android-m2repository
 before_install:     
 - chmod +x gradlew  # 改变gradlew的访问权限
script:
  - ./gradlew assembleDebug
