language: android
 before_install:
 - chmod +x gradlew
android:
  components:
  - tools
  - platform-tools
  - build-tools-23.0.1
  - android-23
  - extra-android-support
  - extra
  - extra-android-m2repository
 jdk:
  - oraclejdk8
script:
  - ./gradlew assembleDebug
